services:
  - type: web
    name: gestion-etude
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: gestion_etude
      - key: SECRET_KEY
        generateValue: true
